server:
  port: 8000

spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0

        - id: product-service
          uri: lb://PRODUCTSERVICE
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=0

        - id: cart-service
          uri: lb://CARTSERVICE
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=0

        - id: order-service
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=0
            - name: RewritePath
              args:
                regexp: /api/orders/(?<segment>.*)
                replacement: /orders/${segment}

        - id: payment-service
          uri: lb://PAYMENTSERVICE
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=0

        - id: notification-service
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=0
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
