version: '3.8'

services:
  # MySQL Database - Optimized for t3.medium
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Admin@12345678
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    command: --default-authentication-plugin=mysql_native_password 
             --innodb-buffer-pool-size=256M 
             --max-connections=50
             --query-cache-size=32M

  # Redis Cache - Memory optimized
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    command: redis-server --maxmemory 200mb --maxmemory-policy allkeys-lru

  # Eureka Server - Reduced memory
  eureka-server:
    build: ./EurekaServer
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=t3medium
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # API Gateway - Memory optimized
  api-gateway:
    build: ./APIGateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=t3medium
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # User Service - Core service
  user-service:
    build: ./UserService
    container_name: user-service
    ports:
      - "8001:8001"
    environment:
      - SPRING_PROFILES_ACTIVE=t3medium
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
      - DB_URL=jdbc:mysql://mysql:3306/userservice?createDatabaseIfNotExist=true
      - DB_USERNAME=root
      - DB_PASSWORD=Admin@12345678
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mysql
      - eureka-server
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Product Service - Core service
  product-service:
    build: ./ProductService
    container_name: product-service
    ports:
      - "8002:8002"
    environment:
      - SPRING_PROFILES_ACTIVE=t3medium
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
      - DB_URL=jdbc:mysql://mysql:3306/productservice?createDatabaseIfNotExist=true
      - DB_USERNAME=root
      - DB_PASSWORD=Admin@12345678
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mysql
      - eureka-server
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Frontend - Lightweight
  frontend:
    build: ./eshopping-zone
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - API_URL=http://localhost:8000
      - APP_NAME=E-Shopping Zone
    depends_on:
      - api-gateway
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Cart Service - Optional (start if needed)
  cart-service:
    build: ./CartService
    container_name: cart-service
    ports:
      - "8003:8003"
    environment:
      - SPRING_PROFILES_ACTIVE=t3medium
      - JAVA_OPTS=-Xms128m -Xmx256m -XX:+UseG1GC
      - DB_URL=jdbc:mysql://mysql:3306/cartservice?createDatabaseIfNotExist=true
      - DB_USERNAME=root
      - DB_PASSWORD=Admin@12345678
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mysql
      - redis
      - eureka-server
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    profiles:
      - extended

volumes:
  mysql_data:

networks:
  default:
    driver: bridge